[package]
name = "summonapp"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
ngx = "0.5.0"
sysinfo = "*"
libc = "0.2.140"

[lib]
name = "summonapp"
crate-type   = ["rlib", "cdylib"]

[patch.crates-io]
ngx = { path = "./ngx-rust" }
